# fly.toml app configuration file generated for portdombo-api on 2025-04-18T20:20:57-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'portdombo-api'
primary_region = 'gig'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '16gb'
cpu_kind = 'shared'
cpus = 8
